### PR TITLE
Fix wrong color for disabled input fields on iOS

### LINKED ISSUE #56: Wrong text color in disabled input fields on iOS
On iOS disabled input fields (TextArea, TextField, NumberField) have wrong text styling:

example

It should look like this:

example2

Adding `-webkit-text-fill-color` CSS property in disabled component should fix this

### PR DESCRIPTION
**Pull request by rwachtler**
- Added -webkit-text-fill-color to createDisabledTextStyles
- Fixes #56

### CODE REVIEW

File: src/components/common/index.js [hunk 1]
```diff
@@ -7,26 +7,29 @@ export const createDisabledTextStyles = () => css`
   color: ${({ theme }) => theme.textDisabled};
   text-shadow: 1px 1px ${({ theme }) => theme.textDisabledShadow};
   /* filter: grayscale(100%); */
+  -webkit-text-fill-color: ${({ theme }) => theme.inputTextDisabled};
```
Comment (rwachtler) [inline src/components/common/index.js]: In my opinion this is a better location to fix this issue, instead of writing it twice into separate components. Other components using the `createDisabledTextStyles()` function shouldn't be affected by this change.

File: src/components/common/index.js [hunk 2]
```diff
@@ -7,26 +7,29 @@ export const createDisabledTextStyles = () => css`
...
 `;
 export const createBoxStyles = () => css`
-    box-sizing: border-box;
-    display: inline-block;
-    background-color: ${({ theme }) => theme.material};
-    color: ${({ theme }) => theme.text};
-  `;
+  box-sizing: border-box;
```
Comment (rwachtler) [inline src/components/common/index.js]: ESLint was complaining quite a lot in this project and I'm not sure if this is some issue with my local setup or not 🤔 If I run `npm run lint` I'm getting quite some errors. I can revert those (auto-fix) changes below if necessary.

**Comment by arturbien** [comment]
@rwachtler  I will review it before the weekend. thanks and welcome to React95 🔥

File: src/components/common/index.js (hunk 2 above)
Comment (arturbien) [reply src/components/common/index.js]: @rwachtler Thanks for the info. @luizbaldi just fixed those eslint issues. Can you pull from the changes from master, auto-fix files and commit it again? thanks!

Comment (rwachtler) [reply src/components/common/index.js]: Thanks for the info. Will do it this evening! 🙂

Comment (rwachtler) [reply src/components/common/index.js]: @arturbien Done! ✅
